### ISSUE TITLE
Chrome Zpl Printer no longer installable?

### ISSUE THREAD

**Issue by tnrich** [brianzinn/zebra-emulator#3]
Hey @brianzinn !

> If you want to preview the label you can install the Zpl Printer extension from the chrome web store and set it up to listen on port 9102

Unfortunately it looks like this extension https://chromewebstore.google.com/detail/zpl-printer/phoidlklenidapnijkabnfdgmadlcmjo is no longer available..?

<img width="1423" alt="image" src="https://github.com/brianzinn/zebra-emulator/assets/2730609/7f47e5bf-dbdf-498f-a537-0fe26af18779">

Any suggestions there. 

Thanks for making this software! We're trying to support a zpl printer but don't actually have one... I'm suprised they don't provide an emulator themselves or at least a fake test device with their printer software!

**Comment by parallels999** [comment]
https://github.com/MrL0co/ZplPrinter/releases

**Comment by tnrich** [comment]
So that'll work with this emulator? @parallels999 

Thanks

**Comment by brianzinn** [comment]
thanks for sharing @parallels999 - so, have you setup and then it runs on port 9102 and acts the same as labelary website?

**Comment by parallels999** [comment]
Yes

**Comment by brianzinn** [comment]
Thanks @tnrich for creating this issue and @parallels999 for a solution. If this doesn't fix for you please re-open.  I have updated the main page readme with instructions.  Cheers.

**Comment by parallels999** [comment]
https://github.com/sbinkert/ZplPrinter/issues/7#issuecomment-1331183007
